### ISSUE TITLE
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject

### ISSUE THREAD

**Issue by staifa** [PaymentHighway/paymenthighway-java-lib#29]
Hi,

I'm trying to get the Java api to work. I'm getting following exception when using payment api on version 1.8-SNAPSHOT. This works on older versions (tried with 1.0-SNAPSHOT), but the older builds are failing on some methods used in current Payment Highway documentation and we want to use the most up-to-date build. 

java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
               BeanSerializer.java:151 com.fasterxml.jackson.databind.ser.BeanSerializer.serialize
    DefaultSerializerProvider.java:292 com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue
                ObjectMapper.java:3672 com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue
                ObjectMapper.java:3048 com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString
                 JsonGenerator.java:24 io.paymenthighway.json.JsonGenerator.createTransactionJson
         PaymentAPIConnection.java:270 io.paymenthighway.connect.PaymentAPIConnection.createSignature
         PaymentAPIConnection.java:229 io.paymenthighway.connect.PaymentAPIConnection.executePost
         PaymentAPIConnection.java:122 io.paymenthighway.connect.PaymentAPIConnection.commitTransaction
                   PaymentAPI.java:139 io.paymenthighway.PaymentAPI.commitTransaction

Any suggestions appreciated,
Frantisek

**Comment by margussipria** [comment]
Do you have `jackson-core` manually set as dependency? This library uses `jackson-databind` version `2.8.3` that requires `jackson-core` version `2.8.0` or better. This seems to be case where core has been set manually and it is older version than required by our library.

This change was done to our library after version 1.4 so thats why version 1.0 did work.

**Comment by staifa** [comment]
Hi, thanks for the reply, the jackson-databind version was set to wrong version by other dependency, thanks for your answer!
